### ISSUE TITLE
Make it more parallel

### ISSUE THREAD

**Issue by nmerket** [NREL/EnergyPlusRegressionTool#31]
It's wonderful that that simulations in this tool are parallelized. However there are a couple of bottlenecks:

- It looks like it waits for all the simulations from one build to finish before starting simulations from the next build.
- The diff-ing is all done serially and takes quite a while.

If you think of the tests as a task graph there's a lot of opportunity for parallelism. There are some python libraries out there, I'm thinking of [Dask](http://docs.dask.org/en/latest/delayed.html) specifically that handle parallel execution of task graphs very nicely. 

![image](https://user-images.githubusercontent.com/5325034/53993071-9999da80-40eb-11e9-92d4-87cf0e8382f8.png)

I know you're probably going to tell me that I am welcome to make a PR with these changes, and someday I might. I just thought I'd write this out while I'm waiting for my regression tests to complete.

**Comment by Myoldmopar** [comment]
~I am~ You are welcome to make a PR with these changes
