### ISSUE TITLE
Add eplusout_perflog.csv output file

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlusRegressionTool#48]
Added a new EnergyPlus output file that is a CSV file and cumulative (should not be deleted between simulations) that is a log of performance and performance settings. Please add this to the CI.

**Comment by Myoldmopar** [comment]
Sounds good. On the cumulative note, CI completely deletes the build folder and entire repo in between runs to ensure nothing lingers between runs and causes mass hysteria.

**Comment by JasonGlazer** [comment]
Understood. I don't expect CI to keep it around but just describing its normal use case.
