### ISSUE TITLE
Requesting louder error message from  idd_parser.py when min-fields > num_fields

### ISSUE THREAD

**Issue by jmythms** [NREL/EnergyPlusRegressionTool#64]
I made an IDF with min fields > num_fields, It generated this error:
`RuntimeError: Object with min-fields > num_fields. ` that was hidden in the rest of the generated text. But the build continued and it was really hard to figure out what was going wrong.

**Comment by Myoldmopar** [comment]
@jmythms can you confirm this was intended for _this_ repo?

**Comment by jmythms** [comment]
Wow. Yeah, sorry that was dumb, my bad! Closing!
