### ISSUE TITLE
Add timestamp to GUI for when last run was executed

### ISSUE THREAD

**Issue by mitchute** [NREL/EnergyPlusRegressionTool#72]
It would be helpful to have the timestep of the last run on the "Results" tab in the GUI.

**Comment by Myoldmopar** [comment]
I don't mind this, but we already do have the timestamps on the results tab:
![image](https://user-images.githubusercontent.com/849824/140234671-7a42f989-05d9-4c37-a53d-72f419cf8f9b.png)

Is that sufficient or should I add it to the results tab?
