### ISSUE TITLE
PyPi project gone, pip fails

### ISSUE THREAD

**Issue by DaJansenGit** [NREL/EnergyPlusRegressionTool#97]
It seems that since today? PyPi project is gone. [Link ](https://pypi.org/project/EnergyPlusRegressionTool/)of this project as well leads to 404 error. `pip install energyplusregressiontool` as well leads to pip install error 

```
ERROR: Could not find a version that satisfies the requirement energyplusregressiontool (from versions: none)
ERROR: No matching distribution found for energyplusregressiontool
 ```

Is this known?

**Comment by Myoldmopar** [comment]
You caught this fast!  :)

I am in the process of gathering several of our EnergyPlus projects and modernizing them and unifying them.  Some of which includes renaming the pypi projects and even the repos/binaries that come with them.  

In this case, you simply need `pip install energyplus-regressions` and you should be good to go.  Another version coming out soon (today?) may have the console script renamed from `eplus_regressions_runner` to `energyplus_regression_gui`.  It's a bit painful to make these changes, but it's an important small step to unifying a bunch of stray EnergyPlus tools/libraries together.  

Thanks for using this and let me know if you have any other questions!

**Comment by DaJansenGit** [comment]
Our pipelines caught it :) 
Thanks to you for the quick response and the development of the tool!

 We will update the package name. If anything goes wrong, I will come back to you.
